package com.anish.expirydatereminder.testing

import com.anish.expirydatereminder.domain.model.AppSettings
import com.anish.expirydatereminder.domain.model.BuiltinCategory
import com.anish.expirydatereminder.domain.model.Category
import com.anish.expirydatereminder.domain.model.DateFormat
import com.anish.expirydatereminder.domain.model.ExpiryDate
import com.anish.expirydatereminder.domain.model.Item
import com.anish.expirydatereminder.domain.model.ItemDraft
import com.anish.expirydatereminder.domain.model.MigrationSummary
import com.anish.expirydatereminder.domain.repository.CategoryRepository
import com.anish.expirydatereminder.domain.repository.ItemRepository
import com.anish.expirydatereminder.domain.repository.SettingsRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.map

/**
 * In-memory stand-ins for the three repositories.
 *
 * Hand-written rather than generated by a mocking library, for two reasons. They enforce the
 * same invariants the SQL does — ids assigned on insert, categories joined onto items,
 * built-ins undeletable — so a test that passes here is not passing against a shape the real
 * database would reject. And they emit through a [MutableStateFlow], so `observeItems`
 * behaves like the SQLDelight query flow it replaces: every write pushes a new list.
 *
 * The point is to test everything above the data layer without a database, not to pretend
 * the data layer does not exist.
 */
class FakeItemRepository(initial: List<Item> = emptyList()) : ItemRepository {

    private val state = MutableStateFlow(initial)
    private var nextId = (initial.maxOfOrNull { it.id } ?: 0L) + 1

    val items: List<Item> get() = state.value

    override fun observeItems(categoryId: Long?): Flow<List<Item>> =
        state.map { list -> if (categoryId == null) list else list.filter { it.categoryId == categoryId } }

    override suspend fun byId(id: Long): Item? = state.value.firstOrNull { it.id == id }

    override suspend fun withName(name: String): List<Item> =
        state.value.filter { it.name.equals(name, ignoreCase = true) }

    override suspend fun add(draft: ItemDraft): Long {
        val id = nextId++
        state.value = state.value + draft.toItem(id)
        return id
    }

    override suspend fun update(draft: ItemDraft) {
        val id = draft.id ?: return
        state.value = state.value.map { if (it.id == id) draft.toItem(id) else it }
    }

    override suspend fun setImagePath(id: Long, path: String?) {
        state.value = state.value.map { if (it.id == id) it.copy(imagePath = path) else it }
    }

    override suspend fun delete(id: Long) {
        state.value = state.value.filterNot { it.id == id }
    }

    override suspend fun deleteAll() {
        state.value = emptyList()
    }

    override suspend fun countExpiringBetween(fromSortKey: Int, toSortKey: Int): Int =
        expiringBetween(fromSortKey, toSortKey).size

    override suspend fun expiringBetween(fromSortKey: Int, toSortKey: Int): List<Item> =
        state.value.filter { it.expiry.sortKey in fromSortKey..toSortKey }.sortedBy { it.expiry.sortKey }

    override suspend fun countInCategory(categoryId: Long): Int = state.value.count { it.categoryId == categoryId }

    override suspend fun allImagePaths(): List<String> = state.value.mapNotNull { it.imagePath }

    /** Mirrors the SQL join, so category name and key are never stale on a fake item. */
    private fun ItemDraft.toItem(id: Long): Item {
        val category = FakeCategoryRepository.BUILTINS.firstOrNull { it.id == categoryId }
        return Item(
            id = id,
            name = name,
            categoryId = categoryId,
            categoryName = category?.name ?: "Uncategorized",
            categoryBuiltinKey = category?.builtinKey,
            expiry = expiry,
            imagePath = imagePath,
            notes = notes,
            createdAt = 0,
            updatedAt = 0,
        )
    }
}

class FakeCategoryRepository(initial: List<Category> = BUILTINS) : CategoryRepository {

    private val state = MutableStateFlow(initial)
    private var nextId = (initial.maxOfOrNull { it.id } ?: 0L) + 1

    override fun observeCategories(): Flow<List<Category>> = state

    override suspend fun all(): List<Category> = state.value

    override suspend fun byId(id: Long): Category? = state.value.firstOrNull { it.id == id }

    override suspend fun byBuiltinKey(key: String): Category? = state.value.firstOrNull { it.builtinKey == key }

    override suspend fun add(name: String): Long? {
        if (state.value.any { it.name.equals(name, ignoreCase = true) }) return null
        val id = nextId++
        state.value = state.value + Category(id = id, name = name, builtinKey = null, isBuiltin = false)
        return id
    }

    override suspend fun rename(id: Long, name: String): Boolean {
        val target = state.value.firstOrNull { it.id == id } ?: return false
        if (target.isBuiltin) return false
        state.value = state.value.map { if (it.id == id) it.copy(name = name) else it }
        return true
    }

    override suspend fun delete(id: Long): Boolean {
        val target = state.value.firstOrNull { it.id == id } ?: return false
        if (target.isBuiltin) return false
        state.value = state.value.filterNot { it.id == id }
        return true
    }

    override suspend fun deleteAllUserCategories() {
        state.value = state.value.filter { it.isBuiltin }
    }

    companion object {
        /** The same set the schema seeds, so ids line up with what the app expects. */
        val BUILTINS: List<Category> = BuiltinCategory.entries.mapIndexed { index, builtin ->
            Category(id = index + 1L, name = builtin.legacyName, builtinKey = builtin.key, isBuiltin = true)
        }

        val UNCATEGORIZED_ID: Long =
            BUILTINS.first { it.builtinKey == BuiltinCategory.UNCATEGORIZED.key }.id
    }
}

class FakeSettingsRepository(initial: AppSettings = AppSettings()) : SettingsRepository {

    private val state = MutableStateFlow(initial)
    var summary: MigrationSummary? = null

    override fun observeSettings(): Flow<AppSettings> = state

    override suspend fun current(): AppSettings = state.value

    override suspend fun setDateFormat(format: DateFormat) {
        state.value = state.value.copy(dateFormat = format)
    }

    override suspend fun setNotificationsEnabled(enabled: Boolean) {
        state.value = state.value.copy(notificationsEnabled = enabled)
    }

    override suspend fun setReminderLeadDays(days: Int) {
        state.value = state.value.copy(reminderLeadDays = days)
    }

    override suspend fun setReminderHour(hour: Int) {
        state.value = state.value.copy(reminderHour = hour)
    }

    override suspend fun migrationSummary(): MigrationSummary? = summary
}

/** Terse item builder, so a test states only the fields it actually cares about. */
fun testItem(
    id: Long = 1,
    name: String = "Item",
    expiry: ExpiryDate = ExpiryDate(1, 1, 2027),
    categoryId: Long = FakeCategoryRepository.UNCATEGORIZED_ID,
    categoryName: String = "Uncategorized",
    categoryBuiltinKey: String? = BuiltinCategory.UNCATEGORIZED.key,
    notes: String? = null,
    imagePath: String? = null,
): Item = Item(
    id = id,
    name = name,
    categoryId = categoryId,
    categoryName = categoryName,
    categoryBuiltinKey = categoryBuiltinKey,
    expiry = expiry,
    imagePath = imagePath,
    notes = notes,
    createdAt = 0,
    updatedAt = 0,
)
